# Site settings
title: title
email: your-email@domain.com
description: void
baseurl: "" # the subpath of your site, e.g. /blog/
url: "#" # the base hostname & protocol for your site
github_username:  toplefty

# Build settings
markdown: kramdown
highlighter: rouge
source: ../src/jekyll
destination: ../../build
keep_files: [css, fonts, images, js]